version: '3.8'

services:
  postgres-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  redis-server:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - mynetwork

networks:
  mynetwork:
