name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create .env file
        run: |
          touch .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          echo DIRECT_URL=${{ secrets.DATABASE_URL }} >> .env
          echo HASH_PASSWORD=${{ secrets.HASH_PASSWORD }} >> .env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
          echo AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} >> .env
          echo AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} >> .env
          echo AWS_DEFAULT_REAGION=${{ secrets.AWS_DEFAULT_REAGION }} >> .env
          echo AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET }} >> .env
          echo APP_URL=${{ secrets.APP_URL }} >> .env
          echo ADMIN_URL=${{ secrets.ADMIN_URL }} >> .env
          echo CLOUD_FRONT=${{ secrets.CLOUD_FRONT }} >> .env
          echo APP_URL=${{ secrets.APP_URL }} >> .env
          echo ADMIN_URL=${{ secrets.ADMIN_URL }} >> .env
          echo ONE_SIGNAL_API_KEY=${{ secrets.ONE_SIGNAL_API_KEY }} >> .env
          echo ONE_SIGNAL_APP_ID=${{ secrets.ONE_SIGNAL_APP_ID }} >> .env
          echo ONE_SIGNAL_URL=${{ secrets.ONE_SIGNAL_URL }} >> .env
          echo AWS_SNS_TOPIC_ARN=${{ secrets.AWS_SNS_TOPIC_ARN }} >> .env
          echo DISABLE_PREVIEWS=${{ secrets.DISABLE_PREVIEWS }} >> .env
          echo API_KEY=${{ secrets.API_KEY }} >> .env
          echo PAGSTAR_BASE_URL=${{ secrets.PAGSTAR_BASE_URL }} >> .env
          echo PAGSTAR_ACCESS_KEY=${{ secrets.PAGSTAR_ACCESS_KEY }} >> .env
          echo PAGSTAR_EMAIL=${{ secrets.PAGSTAR_EMAIL }} >> .env
          echo PAGSTAR_TENANT_ID=${{ secrets.PAGSTAR_TENANT_ID }} >> .env

      - name: Instala as dependencias
        run: yarn install

      - name: Roda prisma generate
        run: yarn prisma generate

      - name: Build project
        run: yarn build

      - name: Roda migrations
        run: yarn prisma migrate deploy

      # - name: Start project
      #   run: pm2 start --name server dist/src/main.js

      # - name: Start studio
      #   run: pm2 start --name studio "npx prisma studio"

      - name: Restart project
        # if: failure()
        run: pm2 restart server

      - name: Restart studio
        # if: failure()
        run: pm2 restart studio
